### ISSUE TITLE
terraform testing

### ISSUE THREAD

**Issue by alasseter-dds** [dod-iac/terraform-aws-lambda-function#6]
Add a simple testing script similar to [terratest](https://github.com/dod-iac/terraform-aws-sqs-queue/blob/master/scripts/terratest) in the sqs-queue repo.
The testing script will build and deploy a simple lambda function, send a notification, and then destroy after testing is complete. It will also generate appropriate error messages on failure.

Expected components:
- terratest script
- examples directory similar to [sqs-queue](https://github.com/dod-iac/terraform-aws-sqs-queue/tree/master/examples/simple) with appropriate .tf files
- test folder similar to [sqs-queue](https://github.com/dod-iac/terraform-aws-sqs-queue/tree/master/test) with .go files

Upon completion of the simple test, I'll expand to additional tests as needed.

@chrisgilmerproj @pjdufour-dds

**Comment by pjdufour-dds** [comment]
The template module now includes terratest fixtures that could be a good reference.  https://github.com/dod-iac/terraform-module-template
